const REPORTES_BASE_URL = process.env.VUE_APP_REPORTES_SLAVE_BASE_URL
const REPORTES_BASE_PATH = process.env.VUE_APP_REPORTES_SLAVE_BASE_PATH
export const REPORTES_URL = REPORTES_BASE_URL + REPORTES_BASE_PATH